### ISSUE TITLE
Crash randomly caused by entity optimization/deletation

### ISSUE THREAD

**Issue by quentin452** [quentin452/TickDynamic#1]
java.util.NoSuchElementException
    at com.wildex999.tickdynamic.listinject.EntityIteratorTimed.next(EntityIteratorTimed.java:83)
    at com.wildex999.tickdynamic.listinject.EntityIteratorTimed.next(EntityIteratorTimed.java:17)
    at com.wildex999.tickdynamic.listinject.ListManagerEntities.get(ListManagerEntities.java:50)
    at com.wildex999.tickdynamic.listinject.ListManagerEntities.get(ListManagerEntities.java:9)
    at net.minecraft.world.World.countEntities(World.java:3958)
    at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:82)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:203)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:750)

**Comment by quentin452** [comment]
Duplicate #25
