### ISSUE TITLE
Occasional Crash with Cubic Chunks installed 

### ISSUE THREAD

**Issue by quentin452** [quentin452/TickDynamic#30]
https://pastebin.com/cT0tP4LX

Happens occasionally, but only on world-loading.

**Comment by quentin452** [comment]
java.util.NoSuchElementException
	at com.wildex999.tickdynamic.listinject.EntityIteratorTimed.next(EntityIteratorTimed.java:83)
	at com.wildex999.tickdynamic.listinject.EntityIteratorTimed.next(EntityIteratorTimed.java:17)
	at com.wildex999.tickdynamic.listinject.ListManagerEntities.get(ListManagerEntities.java:50)
	at com.wildex999.tickdynamic.listinject.ListManagerEntities.get(ListManagerEntities.java:9)
	at net.minecraft.world.World.countEntities(World.java:3950)
	at cubicchunks.world.CubeWorldEntitySpawner.func_77192_a(CubeWorldEntitySpawner.java:84)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by quentin452** [comment]
Should be fixed
