### ISSUE TITLE
java.util.NoSuchElementException: Reached the end of the entity list.

### ISSUE THREAD

**Issue by quentin452** [quentin452/TickDynamic#36]
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Why did you do that?

Time: 2023-08-12 00:09:12 CEST
Description: Exception ticking world entities

java.util.NoSuchElementException: Reached the end of the entity list.
    at com.wildex999.tickdynamic.listinject.EntityIteratorTimed.next(EntityIteratorTimed.java:111)
    at com.wildex999.tickdynamic.listinject.EntityIteratorTimed.next(EntityIteratorTimed.java:14)
    at com.wildex999.tickdynamic.listinject.ListManagerEntities.get(ListManagerEntities.java:50)
    at com.wildex999.tickdynamic.listinject.ListManagerEntities.get(ListManagerEntities.java:9)
    at net.minecraft.world.World.updateEntities(World.java:1742)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:750)

(MixinBooter) Mixins in Stacktrace:
    net.minecraft.server.MinecraftServer:
        zone.rong.loliasm.common.priorities.mixins.MinecraftServerMixin (mixins.priorities.json) [censoredasm5.14.jar]
    net.minecraft.server.integrated.IntegratedServer:
        zone.rong.loliasm.common.crashes.mixins.IntegratedServerMixin (mixins.crashes.json) [censoredasm5.14.jar]
    net/minecraft/server/MinecraftServer:
        zone.rong.loliasm.common.priorities.mixins.MinecraftServerMixin (mixins.priorities.json) [censoredasm5.14.jar]

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: New World
  All players: 0 total; []
  Chunk stats: ServerChunkCache: 3 Drop: 0
  Level seed: -4962289296579670349
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 0 game time, 0 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: ~~ERROR~~ NullPointerException: null

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_372, Azul Systems, Inc.
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
  Memory: 238385056 bytes (227 MB) / 1668284416 bytes (1591 MB) up to 8506048512 bytes (8112 MB)
  JVM Flags: 20 total; -Xmx8192m -Xms8192m -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Xms256m
  IntCache: cache: 0, tcache: 58, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.14 Powered by Forge 14.23.5.2860 9 mods loaded, 9 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID              | Version      | Source                              | Signature                                |
       |:------ |:--------------- |:------------ |:----------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft       | 1.12.2       | minecraft.jar                       | None                                     |
       | LCHIJA | mcp             | 9.42         | minecraft.jar                       | None                                     |
       | LCHIJA | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge           | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | mixinbooter     | 8.3          | minecraft.jar                       | None                                     |
       | LCHIJA | loliasm         | 5.14         | censoredasm5.14.jar                 | None                                     |
       | LCHIJA | erebus          | 1.0.32       | Erebus-1.0.32.jar                   | None                                     |
       | LCHIJA | tickdynamic     | 1.0.4        | TickDynamic-1.12.2-1.0.4.jar        | None                                     |
       | LCHIJA | thebetweenlands | 3.9.6        | TheBetweenlands-3.9.6-universal.jar | 38067d6878811efb38b6a045521cfd80b9b60b38 |
  Loaded coremods (and transformers): MixinBooter (!mixinbooter-8.3.jar)
                                        
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.6-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      LoliASM (censoredasm5.14.jar)
                                        
                                      LoadingPlugin (TickDynamic-1.12.2-1.0.4.jar)
                                        com.wildex999.patcher.TransformerPatcher
                                        com.wildex999.patcher.EntityInjector
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: Tick Dynamic (tickdynamic)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Quentin453'/1151, l='New World', x=167.08, y=72.00, z=292.77]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by quentin452** [comment]
duplicate #3
