### ISSUE TITLE
Reached the end of the entity list

### ISSUE THREAD

**Issue by quentin452** [quentin452/TickDynamic#37]
java.util.NoSuchElementException: Reached the end of the entity list.
	at com.wildex999.tickdynamic.listinject.EntityIteratorTimed.next(EntityIteratorTimed.java:111)
	at com.wildex999.tickdynamic.listinject.EntityIteratorTimed.next(EntityIteratorTimed.java:14)
	at com.wildex999.tickdynamic.listinject.ListManagerEntities.get(ListManagerEntities.java:50)
	at com.wildex999.tickdynamic.listinject.ListManagerEntities.get(ListManagerEntities.java:9)
	at net.minecraft.world.World.updateEntities(World.java:1742)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:750)

**Comment by MoshirMoshir** [comment]
Description: Exception ticking world entities

java.util.NoSuchElementException: Reached the end of the entity list.
    at com.wildex999.tickdynamic.listinject.EntityIteratorTimed.next(EntityIteratorTimed.java:111)
    at com.wildex999.tickdynamic.listinject.EntityIteratorTimed.next(EntityIteratorTimed.java:14)
    at com.wildex999.tickdynamic.listinject.ListManagerEntities.get(ListManagerEntities.java:50)
    at com.wildex999.tickdynamic.listinject.ListManagerEntities.get(ListManagerEntities.java:9)
    at net.minecraft.world.World.updateEntities(World.java:1742)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
