### ISSUE TITLE
Clients just disconnets from server. No crashes on either side. (listIterator is not implemented in TickDynamic's List implementation!)

### ISSUE THREAD

**Issue by aking4125** [quentin452/TickDynamic#40]
Hello,

Upon adding this to the server. Any client with or without this mod just disconnects with no error on the client side. Server log points to this error occurring before the player is kicked: 

`[Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@1a54234f:
org.apache.commons.lang3.NotImplementedException: listIterator is not implemented in TickDynamic's List implementation!
	at com.wildex999.tickdynamic.listinject.ListManager.listIterator(ListManager.java:346) ~[TickDynamic-1.12.2-1.0.5.jar:?]
	at java.util.List.sort(List.java:479) ~[?:1.8.0_382]
	at com.bloodnbonesgaming.calmdownzombieguy.CalmDownZombieGuy.onPlayerUpdate(CalmDownZombieGuy.java:170) ~[CalmDownZombieGuy.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3111_CalmDownZombieGuy_onPlayerUpdate_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:190) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382) [oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173) [pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_382]`
	
The current debug log file is much too large for Github or any pastebin so apologies on that. Here is the .gz of the log testing the error without tick dynamic on the client. Even with it, same issue and error occurs.

[latest.log](https://github.com/quentin452/TickDynamic/files/12395776/latest.log)

[debug-1.log.gz](https://github.com/quentin452/TickDynamic/files/12395777/debug-1.log.gz)

**Comment by quentin452** [comment]
try disabling calm down zombie guy

**Comment by aking4125** [comment]
Sorry for the late response, went on vacation.

Confirmed the mod [calm down zombie guy](https://legacy.curseforge.com/minecraft/mc-mods/calm-down-zombie-guy) caused the issue. Removing that allows the clients to connect.
